### ISSUE TITLE
python3 required for multiqc modules only?

### ISSUE THREAD

**Issue by 256bitKitty** [nf-core/chipseq#155] opened 2020-05-27 22:51 UTC
Hello,
I installed your workflow using the environment.yml file provided in this repo and almost everything worked great; I accidentally ended up with python2.7 in the conda environment. The workflow test run finished successfully for all steps except multiqc where it said: A recent version of Python 3 is required.
This was repeated for deeptools and featureCounts, this is the full message for featureCounts:
  [ERROR  ]         multiqc : Oops! The 'featureCounts' MultiQC module broke...
    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
    If possible, please include a log file that triggers the error - the last file found was:
      None
  ============================================================
  Module featureCounts raised an exception: Traceback (most recent call last):
    File "/work/01912/kitty/lonestar/miniconda3/envs/nf-core-chipseq-1.1.0/bin/multiqc", line 438, in multiqc
      mod = config.avail_modules[this_module].load()
    File "/work/01912/kitty/lonestar/miniconda3/envs/nf-core-chipseq-1.1.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
      return self.resolve()
    File "/work/01912/kitty/lonestar/miniconda3/envs/nf-core-chipseq-1.1.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/work/01912/kitty/lonestar/miniconda3/envs/nf-core-chipseq-1.1.0/lib/python2.7/site-packages/multiqc/modules/featureCounts/__init__.py", line 3, $
      from .feature_counts import MultiqcModule
    File "/work/01912/kitty/lonestar/miniconda3/envs/nf-core-chipseq-1.1.0/lib/python2.7/site-packages/multiqc/modules/featureCounts/feature_counts.py", li$
      from multiqc.modules.base_module import BaseMultiqcModule
    File "/work/01912/kitty/lonestar/miniconda3/envs/nf-core-chipseq-1.1.0/lib/python2.7/site-packages/multiqc/modules/base_module.py", line 10, in <module>
      import markdown
    File "/work/01912/kitty/lonestar/miniconda3/envs/nf-core-chipseq-1.1.0/lib/python2.7/site-packages/markdown/__init__.py", line 27, in <module>
      raise ImportError('A recent version of Python 3 is required.')
  ImportError: A recent version of Python 3 is required.
  ============================================================

I then edited the original yml to include python=3.7 to try creating a new environment with python3 but then conda gave multiple package conflicts. I also tried creating new environments with 3.5 or 3.6 but the conflicts didn't get resolved. I also tried conda install python=3.7 within the successful environment, that did not work either (more package conflicts listed). Do you have a recommended way to have python3 installed, or maybe an environment.yml file that includes it?

If python3 is only needed to get multiqc working with the featureCounts and deeptools, is it OK if I specify the python version as follows:
module add python3/3.7.0
which python3
/opt/apps/intel18/python3/3.7.0/bin/python3

/opt/apps/intel18/python3/3.7.0/bin/python3 -m multiqc .

Thanks!

**Comment by drpatelh** [comment] 2020-05-28 04:10
Hi @256bitKitty ! A [similar issue](https://github.com/nf-core/atacseq/issues/101#issuecomment-633829758) propped up for the `atacseq` pipeline a few days ago. It's most likely because the way in which the Conda environment is resolved has changed since I released the pipeline and isn't entirely unexpected. This isn't great for reproducibility but there isn't much you can do about that other than to use a container as mentioned in the comment I linked to above because you get a static version of all of the pipeline dependencies at the time of release. Are you able to use Docker/Singularity?

**Comment by drpatelh** [comment] 2020-05-28 15:34
Closing this @256bitKitty because I think using Docker/Singularity should overcome this issue 👍 Feel free to re-open if the issue persists or join the #chipseq channel on the [nf-core Slack workspace](https://nf-co.re/join).

**Closed by drpatelh** 2020-05-28 15:34 UTC
Labels: question
