### ISSUE TITLE
CUT&RUN

### ISSUE THREAD

**Issue by ktrns** [nf-core/chipseq#127] opened 2019-12-03 14:07 UTC
Hi there, 

We are dealing with CUT&RUN data for the first time, and you mentioned that it might be useful to add the functionality to Nfcore. I have run the ATAC-seq pipeline so far, and am running the ChIP-seq pipeline now. 

The one and only paper I have read so far is about CUT&RUNTools (Zhu et al, 2019, Genome Biology). 

Let me know what you think! If I find more useful information, I let you know. 
Best wishes
Katrin

**Comment by drpatelh** [comment] 2019-12-17 16:08
https://epigeneticsandchromatin.biomedcentral.com/articles/10.1186/s13072-019-0287-4
https://github.com/FredHutch/SEACR
https://github.com/sarahhainer/uliCUT-RUN
https://bitbucket.org/qzhudfci/cutruntools/src/master/

Some links sent by @houghtos on `nf-core/chipseq` Slack workspace. Given that the pipeline doesnt require controls to call peaks, and the pre-processing steps seem to be pretty much the same I think we should be able to add a parameter to the `atacseq` pipeline to cater for this.

**Comment by houghtos** [comment] 2020-01-02 20:36
From the biomedcentral paper above, it might be worthwhile to keep a macs2 peak calling option - but SEACR seems to be the way to go.  I'd follow the general workflow from ATACseq workflow through alignment and then use bedtools/SEACR for peak calling.  I'm still quite new to cut&run so I'm not 100% on QC, I imagine you can still use the standard ChIP packages.

**Comment by houghtos** [comment] 2020-01-02 20:38
Also important note from Zhu et al. in Genome Biology 2019 paper (sorry for the copy paste, but should probably be incorporated):

> Short fragments are frequently encountered in CUT&RUN experiments due to the fine cutting by pA-MN enzyme. As a result, it is common to expect both mates of DNA fragment to overlap. When the fragment is shorter than the length of a read, then we can expect that adapter run-through will occur. It is thus critical to remove adapter sequences at the end of the reads. To deal with the issues caused by the alignment of short fragments, we made two important modifications to the typical adapter trimming and alignment protocol:
> 1.
> An initial trimming was first performed with Trimmomatic [9], with settings optimized to detect adapter contamination in short-read sequences. Trimmomatic is a template-based trimmer. However, reads containing 6 bp, or less, of adapters are not trimmed. Therefore, a separate tool Kseq was developed to trim up to 6-bp adapters from the 3′ end of each read that was not effectively processed by Trimmomatic. Note that this trimming does not affect the cut site calculation, which counts only the 5′ end of sequences. After trimming, a minimum read length of 25 bp was imposed, as reads smaller than this were hard to align accurately.
> 
>  
> 2.
> Dovetail alignment policy. Bowtie2 [10] aligns each mate of a pair separately and then discards any pairs that have been aligned inconsistently. Dovetail refers to the situation when mates extend past each other. In the default setting, these alignments are discarded. Dovetail is unusual but encountered in CUT&RUN experiments. The --dove-tail setting [10] was enabled to flag this situation as normal or “concordant” instead of elimination of such reads.

**Comment by houghtos** [comment] 2020-02-06 20:50
I've found there's a lot of variability between MACS2 and SEACR with **huge** sensitivity to parameter changes.  We benchmarked a number of samples varying on cell # and enriched binding protein.  

In some cases, SEACR with IgG control was the best fit while others required tuning a numeric threshold or MACS2.  Other variables, such as subsetting by insert size, had major effects on peaks.  For example, in some cases it was optimal to call peaks using SEACR with IgG control on the sorted bam < 120bp.

Pipeline most closely followed [cut and run tools](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1802-4):
1. Trimmomatic for adapter contamination
2. Kseq further trimming for what was missed by trimmomatic
3. Bowtie2 align --dovetail
4. Sort, mark, and remove duplicates
5. Subset bam file by  < and > 120bp

Peaks were then called using MACS2 and SEACR on all resulting bam files and examined for quality control.

**Comment by drpatelh** [comment] 2020-02-07 14:47
Hi @houghtos ! Thanks for the priceless details regarding your benchmarking 😎 

Id imagine using the different tools in steps 1-4 above wont really have much of an impact on the results. May need to look into the `Bowtie2 --dovetail` parameter a bit more. So do you only want to keep overlapping paired-end reads for Cut and Run? 

For step 5, you could just create another rendition of the file below to filter based on those insert sizes and pass that to the pipeline using `--bamtools_filter_pe_config <new_config>`.  So you only want to keep read pairs that have an insert size of less than 120bp?

May need to add `SEACR` to the pipeline though 👍 

Also, just out of interest do you actually get anything useful from your `IgG` samples. In theory, you shouldnt be pulling down much because its an non-specific antibody and shouldnt really pull much down. As a result, the library complexity is quite low and most of the reads are filtered out as duplicates and so renders the data unusable as a control...have you got a MultiQC report or something I can look at where you have analysed these? Be interested to see what yours look like.

**Comment by houghtos** [comment] 2020-02-10 17:39
I can pull the QC files (e.g. mapping rates each step) but may take some time since I committed all non-peak files to archive.

Honestly, unsure how changing 1-4 will result.  Cut & run is _very sensitive_ to parameter changes since it's sparse structure. I've seen pipelines using BWA etc. so it will likely get you reasonable results.  

1. Trimming: The 2-step trimming protocol was implemented due to the predominance of short 25-50bp fragments which skews normal trimming and subsequent aligning methods.  I haven't found much regarding trimming.

2. Aligning: Dovetail option allows mates to be considered concordant if one extends past the other, which are normally discarded.  Dovetail is unusual but encountered in cut&run experiments.  The original author did **not** use dovetail but rather "--local --very-sensitive- local --no-unal --no-mixed --no-discordant --phred33 -I 10 -X 700".  

3. For read pairs < 120bp - this is specific to for examining TFs in cut&run.  This can be made as a default, separate option, or a pipeline that includes multiple outputs.  As indicated in the original paper:

> Separation of sequenced fragments into ≤120 bp and ≥150 bp size classes provides mapping of the local vicinity of a DNA-binding protein, but this can vary depending on the steric access to the DNA by the tethered MNase. Single-end sequencing is not recommended for CUT&RUN, as it sacrifices resolution and discrimination between transcription factors and neighboring nucleosomes. 

I've seen most pipelines include some variation of subsetting results or including them as part of the output for further downstream analysis.  

4. SEACR: There have been questions surrounding SEACR (for example [look at reviewer comments to original author here](https://elifesciences.org/articles/46314)).  Here, I considered 'optimal peaks' between 20-70k.  Everything outside of this range was either <5k _or_  > 170k.  Majority of pipelines I see use MACS2 default.  SEACR is meant to address the sparse properties of cut&run (hence the sensitivity issues).  With MACS2 I often got very few peaks (100-1,000) with the caveat I used q-value < 0.01.  SEACR was incredibly imprecise with peak numbers, but I was more likely able to find optimal peaks.  For example, (1) sample with 100k cells had optimal peak calling as <120bp subsetted with SEACR numerical threshold 0.01 (no IgG control).  (2) Two samples 100k & 200k cells with H3K27ac had few peaks with MACS2 but too many with SEACR numerical threshold 0.01.  Optimal peaks required IgG control.

Some thoughts:

- Peak calling can be imprecise.  It's probably best to allow the user flexibility to re-call peaks if there are too many or too few per library.  SEACR is available as a web tool for this purpose here: https://seacr.fredhutch.org/.  MACS2 or HOMER may be better options for default peak calling with adjusted parameters. 
- IgG control is used to determine the [numeric threshold](https://epigeneticsandchromatin.biomedcentral.com/articles/10.1186/s13072-019-0287-4).  Signal blocks from the input files that overlap with IgG blocks are also filtered out as means to reduce false positives. However, I imagine the latter step can be handled by removing duplicates and multimapping reads beforehand.

**Comment by houghtos** [comment] 2020-03-04 15:35
Lab which published cut & run uploaded a new pipeline here:

https://pypi.org/project/henipipe/

**Comment by rrdavis77** [comment] 2020-07-31 01:38
Hi @houghtos and @drpatelh !

Are there any beta releases of this CUT&RUN pipeline that we can test?

Thanks!

**Comment by drpatelh** [comment] 2020-07-31 07:52
Hi @rrdavis77 ! Unfortunately, I haven't had the time to look at this properly or to write any sort of implementation, and I don't envisage that changing any time soon 😅. I am still uncertain as to how much work it will take to include this as part of nf-core/atacseq or nf-core/chipseq or whether we have an independent pipeline. 

@ktrns managed to run the nf-core/atacseq pipeline on her data for initial assessment but I imagine this isn't ideal for a proper analysis.

**Comment by houghtos** [comment] 2020-08-02 17:36
@rrdavis77 @drpatelh 
Suggest looking at "Heni Pipeline", a python wrapper designed for use in an HPC environment published by lab who developed the experimental protocol:
https://pypi.org/project/henipipe/

If you do not have access to an HPC environment to run this, reviewing the code for their workflow is also helpful.

My experience with cut&run is the sparse nature of the data makes it sensitive to noise.  Unfortunately there is no standardized workflow such as 10x has with cellranger.  There are a lot of public CNR pipelines using a variety of different adapter trimming methods, aligners, etc. but I've settled on following the Henikoff lab's general workflow (worth noting I haven't looked for or reviewed any new literature in a number of months due to other priorities).     

For peak calling, I believe their first manuscript used MACS2 since reviewers had questions about SEACR... but there have been followup papers addressing this.  For whatever workflow you use, I'd suggest checking peaks with both callers.  My experience related to peak calling w/ CNR is approaches (MACS2 vs SEACR) and parameters (e.g. use of control input, q-value cutoffs) is incredibly sensitive with wide variability.

**Comment by houghtos** [comment] 2020-08-04 19:56
Wanted to add C&R  may actually produce identical molecules due to base pair resolution of footprints obtained by MNase (differing from ChIP-seq).  It's observed high yield experiments produce "PCR duplicates" that are actually biologically meaningful molecules (100k+ cells & histone modification antibodies). Something to keep in mind for post alignment QC in removing duplicates.

**Comment by ktrns** [comment] 2020-08-20 19:03
Dear @drpatelh, 

My client has moved from CUT&Run to CUT&Tag. 
https://www.protocols.io/view/cut-amp-tag-data-processing-and-analysis-tutorial-bjk2kkye

In case this is of interest for you as well. I haven't had time yet to look into details and which existing pipeline might be most appropriate (atacseq or chipseq), but will let you know once I progress. I have just gotten the data and am looking into my previous GitHub issues here :-). 

Best wishes
Katrin

**Comment by chris-cheshire** [comment] 2020-11-13 11:44
Hi all, just to let you know we are actively developing a CUT&TAG and a CUT&RUN nextflow DSL2 pipeline. We plan to release this to nf-core early next year.

**Comment by houghtos** [comment] 2020-11-13 16:08
Members of Henikoff lab have been very helpful in our development of a SLURM based one.  Also Henipipe was a good jumping off point for a workflow (including ecoli spike in etc. normalization) though documentation was a little behind most recent version.

**Comment by NathanSkene** [comment] 2020-12-10 06:03
Thought I'd chip in here that I'm looking forward to the release of the pipeline that @chris-cheshire mentions! If you had a beta-tester we can give it a go.

**Comment by chris-cheshire** [comment] 2020-12-10 09:32
@NathanSkene we will def need testers in the new year! There is a cutandrun slack channel on nf-core if you wanted to follow development on there.

**Comment by chris-cheshire** [comment] 2020-12-10 09:33
> Members of Henikoff lab have been very helpful in our development of a SLURM based one. Also Henipipe was a good jumping off point for a workflow (including ecoli spike in etc. normalization) though documentation was a little behind most recent version.

@houghtos Yes we are basing our pipeline on the tutorial posted here: https://www.protocols.io/view/cut-amp-tag-data-processing-and-analysis-tutorial-bjk2kkye

**Comment by EllieDuan** [comment] 2021-02-08 16:33
Hello all,

Thanks for the very informative discussions and posters here. I'm wondering if anyone worked on TF Cut and Run data? Any good pipeline/parameters to follow? Do you use IgG control? I found very few peaks (100-1000) in my sample using SEACR numerical threshold 0.01 (no IgG control). So we are not sure if it is caused by sample preparation or by data analysis parameters. My bam files become small after filtering out low-quality reads, duplicates reads, and > 120bp insert size.  

Have you compared Cut and Run data with ChIP-seq data for the same TF? Thank you!

**Comment by drpatelh** [comment] 2021-02-08 17:08
Hi @EllieDuan @chris-cheshire is developing a `cutandrun` pipeline. It may be easier to have a discussion by joining the [nf-core Slack workspace](https://nf-co.re/join) and join the #cutandrun channel there :)

**Closed** 2022-03-02 16:54 UTC
Labels: feature-request
