### ISSUE TITLE
Error with NextSeq trimming

### ISSUE THREAD

**Issue by gitMakeCoffee** [nf-core/chipseq#375] opened 2023-12-22 02:22 UTC
### Description of the bug

Tried to run the pipeline with the ```--trim_nextseq```. However, Nextflow throws an error after barely a couple of seconds:
```
N E X T F L O W  ~  version 23.10.0
ERROR ~ Unable to parse config file: '/lustre/project/123456/user/.NEXTFLOW/nf-core-chipseq_2.0.0/2_0_0/nextflow.config'

  Cannot compare java.lang.Boolean with value 'true' and java.lang.Integer with value '0'


 -- Check '.nextflow.log' file for details
```

Strangely, this error resolves once the option is removed, and the pipeline launches correctly.

### Command used and terminal output

```console
nextflow run -profile singularity,cluster -c $HOME/.nextflow/moreTime.config -with-report report.html -with-dag dag.png -with-timeline timeline.html --genome GRCh38 --input sampleSheet.csv --read_length 50 --outdir result
```

### Relevant files

```
Dec.-21 21:13:00.392 [main] DEBUG nextflow.cli.Launcher - $> nextflow run -profile singularity,cluster -c $HOME/.nextflow/moreTime.config -with-report report.html -with-dag dag.png -with-timeline timeline.html --genome GRCh38 --input sampleSheet.csv --read_length 50 --outdir result
Dec.-21 21:13:00.455 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.10.0
Dec.-21 21:13:00.476 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/user/.nextflow/plugins; core-plugins: nf-amazon@2.1.4,nf-azure@1.3.2,nf-cloudcache@0.3.0,nf-codecommit@0.1.5,nf-console@1.0.6,nf-ga4gh@1.1.0,nf-google@1.8.3,nf-tower@1.6.3,nf-wave@1.0.0
Dec.-21 21:13:00.487 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Dec.-21 21:13:00.488 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Dec.-21 21:13:00.491 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Dec.-21 21:13:00.500 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Dec.-21 21:13:01.375 [main] DEBUG nextflow.config.ConfigBuilder - Found config home: /home/user/.nextflow/config
Dec.-21 21:13:01.375 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /lustre/project/123456/user/.NEXTFLOW/nf-core-chipseq_2.0.0/2_0_0/nextflow.config
Dec.-21 21:13:01.377 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /home/user/.nextflow/moreTime.config
Dec.-21 21:13:01.378 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/user/.nextflow/config
Dec.-21 21:13:01.378 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /lustre/project/123456/user/.NEXTFLOW/nf-core-chipseq_2.0.0/2_0_0/nextflow.config
Dec.-21 21:13:01.378 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/user/.nextflow/moreTime.config
Dec.-21 21:13:01.386 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity,cluster`
Dec.-21 21:13:01.442 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity,cluster`
Dec.-21 21:13:02.917 [main] ERROR nextflow.cli.Launcher - Unable to parse config file: '/lustre/project/123456/user/.NEXTFLOW/nf-core-chipseq_2.0.0/2_0_0/nextflow.config'

  Cannot compare java.lang.Boolean with value 'true' and java.lang.Integer with value '0'

java.lang.IllegalArgumentException: Cannot compare java.lang.Boolean with value 'true' and java.lang.Integer with value '0'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareToWithEqualityCheck(DefaultTypeTransformation.java:598)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareTo(DefaultTypeTransformation.java:533)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareTo(ScriptBytecodeAdapter.java:716)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareGreaterThan(ScriptBytecodeAdapter.java:766)
	at Script7B611291D57182C185BC9F045AD67BCA$_run_closure4$_closure58.doCall(Script7B611291D57182C185BC9F045AD67BCA:148)
	at Script7B611291D57182C185BC9F045AD67BCA$_run_closure4$_closure58.doCall(Script7B611291D57182C185BC9F045AD67BCA)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:427)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:83)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1118)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
	at groovy.lang.MetaObjectProtocol$invokeMethod$0.call(Unknown Source)
	at nextflow.config.ConfigBase$_includeConfig_closure2.doCall(ConfigBase.groovy:114)
	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:83)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1118)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:814)
	at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
	at groovy.lang.Script.invokeMethod(Script.java:96)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:408)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:348)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at Script7B611291D57182C185BC9F045AD67BCA$_run_closure4.doCall(Script7B611291D57182C185BC9F045AD67BCA:145)
	at Script7B611291D57182C185BC9F045AD67BCA$_run_closure4.doCall(Script7B611291D57182C185BC9F045AD67BCA)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:427)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:83)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1118)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
	at groovy.lang.MetaObjectProtocol$invokeMethod$0.call(Unknown Source)
	at nextflow.config.ConfigBase$_includeConfig_closure2.doCall(ConfigBase.groovy:114)
	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:83)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1118)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at Script7B611291D57182C185BC9F045AD67BCA.run(Script7B611291D57182C185BC9F045AD67BCA:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1042)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1128)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovy.lang.Closure.call(Closure.java:406)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at nextflow.config.ConfigBase.includeConfig(ConfigBase.groovy:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.reflection.CachedMethod$invoke.call(Unknown Source)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:448)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:83)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1118)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:226)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at _nf_config_444ac8c6.run(_nf_config_444ac8c6:239)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.reflection.CachedMethod$invoke.call(Unknown Source)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:448)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:83)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1118)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:476)
	at nextflow.config.ConfigParser$parse$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at nextflow.config.ConfigParser$parse$0.callCurrent(Unknown Source)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:303)
	at nextflow.config.ConfigParser$parse$6.call(Unknown Source)
	at nextflow.config.ConfigBuilder.parse0(ConfigBuilder.groovy:434)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:420)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:370)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:315)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:806)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:819)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:324)
	at nextflow.cli.Launcher.run(Launcher.groovy:499)
	at nextflow.cli.Launcher.main(Launcher.groovy:670)
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Boolean (java.lang.Integer and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at java.base/java.lang.Boolean.compareTo(Boolean.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1024)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1015)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareToWithEqualityCheck(DefaultTypeTransformation.java:584)
	... 185 common frames omitted
```

### System information

Nextflow v23.10.0.5889
Ran on Canadian HPC
Slurm
Singularity
Pipeline v2.0.0

**Comment by JoseEspinosa** [comment] 2024-07-23 13:30
Sorry for the late reply, probably not useful for you anymore but just someone finds this issue in the future.
The problem is that this parameter expects an `integer` as you can see in the docs, [here](https://nf-co.re/chipseq/2.0.0/parameters/#trim_nextseq)

**Comment by JoseEspinosa** [comment] 2024-07-24 10:38
Will close it now, feel free to reach out if you have any further issue.

**Closed by JoseEspinosa** 2024-07-24 10:38 UTC
Labels: question
